image: circleci/openjdk:11-jdk-browsers

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  APP_NAME: "speedracer-producer-api"
  CLUSTER_PRODUCTION: "teresa-prod-logistica-a.magazineluiza.com.br"
  CLUSTER_STAGE: "teresa-gcp-staging.magazineluiza.com.br"

cache:
  key: m2-cache
  paths:
    - .m2/
    - target

stages:
  - build
  - test
  - sonar
  - fortify  
  - deploy

build: &build
  stage: build
  cache: {}
  script:
    - mvn compile -DskipTests -s settings.xml
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^production-.+/

build-commit:
  <<: *build
  only:
    refs:
      - branches

test: &test
  stage: test
  script:
    - mvn test -s settings.xml
  only:
    refs:
      - branches

test-tag:
  <<: *test
  script:
    - mvn test -s settings.xml
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^production-.*/

fortify:
  stage: fortify
  image: gcr.io/magalu-infra-project/magalu-fortify:v0.1.0
  before_script:
    - sed -i "s/TPL_FORTIFY_CLIENT_TOKEN/$FORTIFY_CLIENT_TOKEN/g" ./fortify.properties
  script:
    - cp ./fortify.properties /etc/fortify/fortify.properties
    - java -jar /etc/fortify/fortify-api.jar create -name $APP_NAME -version $CI_COMMIT_REF_NAME
    - /opt/fortify/bin/sourceanalyzer -Xmx2g -b $CI_COMMIT_REF_NAME .
    - /opt/fortify/bin/cloudscan -url https://fortifycontroller.luizalabs.com/cloud-ctrl start -upload -uptoken $FORTIFY_TOKEN -application $APP_NAME -version $CI_COMMIT_REF_NAME -b $CI_COMMIT_REF_NAME -scan
  tags:
    - fortify

sonar:
  stage: sonar
  script:
    - mvn sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -s settings.xml
    - cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  coverage: "/Total.*?([0-9]{1,3})%/"
  only:
    - master

deploy-stage:
  stage: deploy
  before_script:
    - mvn package -s settings.xml -DskipTests
  script:
    - ./deploy/deploy.sh $CLUSTER_STAGE $APP_NAME
  only:
    - stage

deploy-production:
  stage: deploy
  before_script:
    - mvn package -s settings.xml -DskipTests
  script:
    - ./deploy/deploy.sh $CLUSTER_PRODUCTION $APP_NAME
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^production-.*/

