timezone: ${TIMEZONE:America/Sao_Paulo}

server:
  port: ${PORT:9002}
  servlet:
    contextPath: /information-address
    
spring:
  main:
    banner-mode: "off"
  profiles:
     active: ${env:hml}
  application:
    name: InformationAddressAPI
       
        
security:
  jwt:
      uri: "/**"
      prefix: ${JWT_PREFIX:Bearer}
      secret: ${JWT_SECRET:cb492761801832cd2854e03a86e6776f}

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true 
  client:
    config:
      default:
        connectTimeout: ${API_TIMEOUT:10000}
        readTimeout: ${API_TIMEOUT:10000}
        loggerLevel: ${FEIGN_LOGGER_LEVEL:full}
        
viacep:
  api:
    url: ${CEP_API_URL:https://viacep.com.br}
  
info:
  app:
    encoding: '@project.build.sourceEncoding@'
  java:
    source: '@java.version@'
    target: '@java.version@'
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
 
management:
  endpoint:
    health:
      show-details: always



