version: 2
references:
  defaults: &defaults
    working_directory: ~/information/address
    docker:
      - image: circleci/openjdk:11-jdk-browsers
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build project
          command: mvn clean package -DskipTests
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test project
          command: mvn clean test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
